### ISSUE TITLE
View which day has a detail or event

### ISSUE THREAD

**Issue by nelsaow** [LoKiLyn/Calendar#1]
I couldn't figure out how can I set a mark or something like it, which the user can know from the calendar days which has added detail or event. Can you help me? Thanks

**Comment by Lino-saur** [comment]
Thanks for your advice. I'll do it soon.

**Comment by Lino-saur** [comment]
Fixed ^-^ . The cells which added detail or event are marked with brown color.

**Comment by nelsaow** [comment]
Thanks! It helped me a lot.
